---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
  name: inspec

platforms:
  - name: windows-7
  - name: windows-10
  - name: windows-2008r2
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    attributes:
      workstation:
        source_destination: 'c:/source'
