name 'workstation'
maintainer 'Derek Groh'
maintainer_email 'derekgroh@gmail.com'
license 'all_rights'
description 'Installs/Configures workstation'
long_description 'Installs/Configures workstation'
version '0.1.0'
issues_url 'https://github.com/derekgroh/workstation/issues'
source_url 'https://github.com/derekgroh/workstation.git'
depends 'winbox'
depends 'git'
